In [12]:
# Importing NumPy
import numpy as np

#Creating NumPy Array
arr1 = np.array([1, 2, 3, 4, 5])
zeros_arr = np.zeros(5)
ones_arr = np.ones((3, 4))
empty_arr = np.empty((2, 2))
range_arr = np.arange(0, 10, 2)

# Adding Attributes to the Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

# Slicing & Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1:4])

# Basic Operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 * 2)

#ufuncs
arr = np.array([0, np.pi/2, np.pi])
print(np.sin(arr))

# Linear Algebra
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))  # Output: [[19, 22], [43, 50]] - Matrix multiplication


(2, 3)
int64
2
1
[2 3 4]
[5 7 9]
[2 4 6]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[[19 22]
 [43 50]]
