In [13]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

# Accessing elements
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slicing array:", arr[1:4])

# Changing elements
arr[2] = 10
print("Modified Array:", arr)

# Adding elements
new_arr = np.append(arr, [6, 7, 8])
print("Array after append:", new_arr)

# Removing elements
removed_arr = np.delete(new_arr, [0, 3])
print("Array after deletion:", removed_arr)

# Reshaping array
reshaped_arr = removed_arr.reshape(2, 3)
print("Reshaped Array:")
print(reshaped_arr)

# Arithmetic operations
addition_arr = reshaped_arr + 2
print("Array after addition:")
print(addition_arr)

# Element-wise multiplication
multiply_arr = addition_arr * 3
print("Array after multiplication:")
print(multiply_arr)

# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_result = np.dot(matrix1, matrix2)
print("Matrix multiplication result:")
print(matrix_result)


Original Array: [1 2 3 4 5]
First element: 1
Last element: 5
Slicing array: [2 3 4]
Modified Array: [ 1  2 10  4  5]
Array after append: [ 1  2 10  4  5  6  7  8]
Array after deletion: [ 2 10  5  6  7  8]
Reshaped Array:
[[ 2 10  5]
 [ 6  7  8]]
Array after addition:
[[ 4 12  7]
 [ 8  9 10]]
Array after multiplication:
[[12 36 21]
 [24 27 30]]
Matrix multiplication result:
[[19 22]
 [43 50]]
